
# Note: following code are generated by AI

# Step 1: Install required libraries if not already installed
if (!requireNamespace("sf", quietly = TRUE)) install.packages("sf")
if (!requireNamespace("osmdata", quietly = TRUE)) install.packages("osmdata")
if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")

# Step 2: Load the libraries
library(sf)         # For handling spatial data
library(osmdata)    # For downloading OpenStreetMap data
library(ggplot2)    # For creating the map visualization

# Step 3: Define the area of interest (Philadelphia)
# This retrieves the geographical bounding box for Philadelphia
philly_bbox <- getbb("Philadelphia, Pennsylvania, USA")

# Step 4: Fetch road network data from OpenStreetMap
# We use "highway" as the key to get all types of roads
philly_highways <- opq(bbox = philly_bbox) %>%     # Define the query for Philadelphia's bounding box
  add_osm_feature(key = "highway") %>%            # Add a filter for highways/roads
  osmdata_sf()                                    # Download data in Simple Features (sf) format

# Step 5: Extract road data from the downloaded OSM data
roads <- philly_highways$osm_lines                # Extract roads as line geometries

# Step 6: Plot the road network using ggplot2
ggplot() +
  geom_sf(data = roads, color = "blue", size = 0.3, alpha = 0.7) +  # Plot roads in blue
  labs(
    title = "Philadelphia Traffic Network",                      # Map title
    subtitle = "Data Source: OpenStreetMap",                     # Subtitle with data source
    caption = "Visualization created using R and ChatGPT"        # Add attribution in the caption
  ) +
  theme_minimal()                                                # Use a clean and minimal theme

